version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - app

  app:
    image: httpd:latest
    volumes:
      - ./html:/usr/local/apache2/htdocs

